### ISSUE TITLE
java.lang.IllegalStateException:You need to init matrix before work!

### ISSUE THREAD

**Issue by gyqsophila** [Cleveroad/AdaptiveTableLayout#12]
When I reload a Activity contains a AdaptiveTableLayout ,sometimes it produce a IllegalStateException, but sometimes not.

``` java
java.lang.IllegalStateException: You need to init matrix before work!
                        at com.cleveroad.adaptivetablelayout.AdaptiveTableManager.checkForInit(AdaptiveTableManager.java:66)
                        at com.cleveroad.adaptivetablelayout.AdaptiveTableManager.getColumnByXWithShift(AdaptiveTableManager.java:226)
                        at com.cleveroad.adaptivetablelayout.AdaptiveTableLayout.addViewHolders(AdaptiveTableLayout.java:790)
                        at com.cleveroad.adaptivetablelayout.AdaptiveTableLayout.notifyDataSetChanged(AdaptiveTableLayout.java:1519)
                        at com.alphagao.youda.ui.activity.StadiumActivity$3.run(StadiumActivity.java:276)
```

**Comment by yarovoiag** [comment]
I think you try to work with AdaptiveTableLayout without adapter.

**Comment by yarovoiag** [comment]
Could you provide more details with example.
