### ISSUE TITLE
AdaptiveTableLayout crashes when loading an empty CSV

### ISSUE THREAD

**Issue by vyguera** [Cleveroad/AdaptiveTableLayout#45]
I get following exception when trying to use AdaptiveTableLayout when loading an adapter with no data. Same happens on sample if loaded an empty CSV:

java.lang.NegativeArraySizeException: -1
	at com.cleveroad.adaptivetablelayout.AdaptiveTableManager.init(AdaptiveTableManager.java:59)
	at com.cleveroad.adaptivetablelayout.AdaptiveTableLayout.initItems(AdaptiveTableLayout.java:253)
	at com.cleveroad.adaptivetablelayout.AdaptiveTableLayout.setAdapter(AdaptiveTableLayout.java:312)
	at com.cleveroad.sample.ui.TableLayoutFragment.initAdapter(TableLayoutFragment.java:316)
	at com.cleveroad.sample.ui.TableLayoutFragment.onCreateView(TableLayoutFragment.java:134)

**Comment by vyguera** [comment]
This is solved in Pull Request #41
