### ISSUE TITLE
  java.lang.NegativeArraySizeException: -1

### ISSUE THREAD

**Issue by mortezasun** [Cleveroad/AdaptiveTableLayout#7]
when run app in persian-fa language get this error
`AndroidRuntime: FATAL EXCEPTION: main
                                                                                        Process: com.develotter.adaptivetablelayouttest, PID: 27698
                                                                                        java.lang.NegativeArraySizeException: -1
                                                                                            at com.cleveroad.adaptivetablelayout.AdaptiveTableManager.init(AdaptiveTableManager.java:59)
                                                                                            at com.cleveroad.adaptivetablelayout.AdaptiveTableLayout.initItems(AdaptiveTableLayout.java:224)
                                                                                            at com.cleveroad.adaptivetablelayout.AdaptiveTableLayout.onLayout(AdaptiveTableLayout.java:143)
                                                                                            at android.view.View.layout(View.java:17993)
                                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5817)
                                                                                            at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
                                                                                            at android.view.View.layout(View.java:17993)
                                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5817)
                                                                                            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
                                                                                            at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
                                                                                            at android.view.View.layout(View.java:17993)
                                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5817)
                                                                                            at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
                                                                                            at android.view.View.layout(View.java:17993)
                                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5817)
                                                                                            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
                                                                                            at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
                                                                                            at android.view.View.layout(View.java:17993)
                                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5817)
                                                                                            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
                                                                                            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                                            at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                                            at android.view.View.layout(View.java:17993)
                                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5817)
                                                                                            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
                                                                                            at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
                                                                                            at android.view.View.layout(View.java:17993)
                                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5817)
                                                                                            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
                                                                                            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                                            at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                                            at android.view.View.layout(View.java:17993)
                                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5817)
                                                                                            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
                                                                                            at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
                                                                                            at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:3145)
                                                                                            at android.view.View.layout(View.java:17993)
                                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5817)
                                                                                            at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2755)
                                                                                            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2456)
                                                                                            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1524)
                                                                                            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7520)
                                                                                            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
                                                                                            at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                                            at android.view.Choreographer.doFrame(Choreographer.java:622)
                                                                                            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
                                                                                            at android.os.Handler.handleCallback(Handler.java:739)
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                            at android.os.Looper.loop(Looper.java:148)
                                                                                            at android.app.ActivityThread.main(ActivityThread.java:7303)
                                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)`

**Comment by yarovoiag** [comment]
Fixed in version 1.1.1
